---

- hosts: all
  become: true
  tasks:

  - name: install apache and php packages for Ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
      
      
  - name: start apache
    service:
      name: apache2
      state: started
      enabled: yes
